"""empty message

Revision ID: 950e4cf1d1a9
Revises: 2884a8b4e7a7
Create Date: 2024-02-07 14:09:02.854051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950e4cf1d1a9'
down_revision = '2884a8b4e7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('services', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'created_at')
    # ### end Alembic commands ###
